/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.swapswire.sw_api;

public final class SW_DealerDealState {
  public final static SW_DealerDealState SWDDS_Err = new SW_DealerDealState("SWDDS_Err", -1);
  public final static SW_DealerDealState SWDDS_NotPickedUp = new SW_DealerDealState("SWDDS_NotPickedUp");
  public final static SW_DealerDealState SWDDS_PickedUp = new SW_DealerDealState("SWDDS_PickedUp");
  public final static SW_DealerDealState SWDDS_Accepted = new SW_DealerDealState("SWDDS_Accepted");
  public final static SW_DealerDealState SWDDS_Rejected = new SW_DealerDealState("SWDDS_Rejected");
  public final static SW_DealerDealState SWDDS_RequestedRevision = new SW_DealerDealState("SWDDS_RequestedRevision");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SW_DealerDealState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SW_DealerDealState.class + " with value " + swigValue);
  }

  private SW_DealerDealState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SW_DealerDealState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SW_DealerDealState(String swigName, SW_DealerDealState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SW_DealerDealState[] swigValues = { SWDDS_Err, SWDDS_NotPickedUp, SWDDS_PickedUp, SWDDS_Accepted, SWDDS_Rejected, SWDDS_RequestedRevision };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

