/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.swapswire.sw_api;

public class SW_DealNotifyData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SW_DealNotifyData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SW_DealNotifyData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public int getLh() {
    return SWAPILink.SW_DealNotifyData_lh_get(swigCPtr, this);
  }

  public SWIGTYPE_p_void getClientData() {
    long cPtr = SWAPILink.SW_DealNotifyData_clientData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public String getBrokerId() {
    return SWAPILink.SW_DealNotifyData_brokerId_get(swigCPtr, this);
  }

  public long getDealId() {
    return SWAPILink.SW_DealNotifyData_dealId_get(swigCPtr, this);
  }

  public int getMajorVer() {
    return SWAPILink.SW_DealNotifyData_majorVer_get(swigCPtr, this);
  }

  public int getMinorVer() {
    return SWAPILink.SW_DealNotifyData_minorVer_get(swigCPtr, this);
  }

  public int getPrivateVer() {
    return SWAPILink.SW_DealNotifyData_privateVer_get(swigCPtr, this);
  }

  public int getSide() {
    return SWAPILink.SW_DealNotifyData_side_get(swigCPtr, this);
  }

  public String getPrevDVH() {
    return SWAPILink.SW_DealNotifyData_prevDVH_get(swigCPtr, this);
  }

  public String getDvh() {
    return SWAPILink.SW_DealNotifyData_dvh_get(swigCPtr, this);
  }

  public SW_DealState getNewState() {
    return SW_DealState.swigToEnum(SWAPILink.SW_DealNotifyData_newState_get(swigCPtr, this));
  }

  public String getNewStateStr() {
    return SWAPILink.SW_DealNotifyData_newStateStr_get(swigCPtr, this);
  }

  public String getContractState() {
    return SWAPILink.SW_DealNotifyData_contractState_get(swigCPtr, this);
  }

  public String getProductType() {
    return SWAPILink.SW_DealNotifyData_productType_get(swigCPtr, this);
  }

  public long getTradeAttrFlags() {
    return SWAPILink.SW_DealNotifyData_tradeAttrFlags_get(swigCPtr, this);
  }

}
