/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.swapswire.sw_api;

public class SWAPILinkModule implements SWAPILinkModuleConstants {
  public static int SW_Initialise(String iniFile, int apiVersion) {
    return SWAPILink.SW_Initialise(iniFile, apiVersion);
  }

  public static int SW_Connect(String server, int timeout, Object tag, int[] sh_out) {
    return SWAPILink.SW_Connect(server, timeout, tag, sh_out);
  }

  public static int SW_Disconnect(int sh) {
    return SWAPILink.SW_Disconnect(sh);
  }

  public static int SW_SetApplicationInfo(int sh, String infoString) {
    return SWAPILink.SW_SetApplicationInfo(sh, infoString);
  }

  public static int SW_Login(int sh, String userID, String password, int[] lh_out) {
    return SWAPILink.SW_Login(sh, userID, password, lh_out);
  }

  public static int SW_LoginOnBehalf(int sh, String adminID, String password, String userID, int[] lh_out) {
    return SWAPILink.SW_LoginOnBehalf(sh, adminID, password, userID, lh_out);
  }

  public static int SW_Logout(int lh) {
    return SWAPILink.SW_Logout(lh);
  }

  public static int SW_SetCapability(int lh, String capability, int enable) {
    return SWAPILink.SW_SetCapability(lh, capability, enable);
  }

  public static int SW_GetCapabilities(int lh, String[] result_out) {
    return SWAPILink.SW_GetCapabilities(lh, result_out);
  }

  public static int SW_ChangePassword(int sh, String userID, String password, String newPassword) {
    return SWAPILink.SW_ChangePassword(sh, userID, password, newPassword);
  }

  public static int SW_SetCallbackMode(SW_CallbackMode callbackMode) {
    return SWAPILink.SW_SetCallbackMode(callbackMode.swigValue());
  }

  public static int SW_RegisterSessionStateCallback(Object cfunc) {
    return SWAPILink.SW_RegisterSessionStateCallback(cfunc);
  }

  public static int SW_RegisterDealNotifyCallback(int lh, Object tag) {
    return SWAPILink.SW_RegisterDealNotifyCallback(lh, tag);
  }

  public static int SW_RegisterDealNotifyExCallback(int lh, Object tag) {
    return SWAPILink.SW_RegisterDealNotifyExCallback(lh, tag);
  }

  public static int SW_RegisterBatchCallback(int lh, Object tag) {
    return SWAPILink.SW_RegisterBatchCallback(lh, tag);
  }

  public static int SW_Poll(int maxtime, int timeout) {
    return SWAPILink.SW_Poll(maxtime, timeout);
  }

  public static int SW_GetErrorDescription(int errorCode, String[] result_out) {
    return SWAPILink.SW_GetErrorDescription(errorCode, result_out);
  }

  public static String SW_ErrorStr(int errorCode) {
    return SWAPILink.SW_ErrorStr(errorCode);
  }

  public static int SW_GetLastErrorSpecificsEx(String[] result_out) {
    return SWAPILink.SW_GetLastErrorSpecificsEx(result_out);
  }

  public static String SW_GetLastErrorSpecifics() {
    return SWAPILink.SW_GetLastErrorSpecifics();
  }

  public static int SW_GetAddressList(int lh, String addressListQueryXML, String[] resultXML_out) {
    return SWAPILink.SW_GetAddressList(lh, addressListQueryXML, resultXML_out);
  }

  public static int SW_GetMyUserInfo(int lh, String[] resultXML_out) {
    return SWAPILink.SW_GetMyUserInfo(lh, resultXML_out);
  }

  public static int SW_GetStaticData(int lh, String dataCategory, String dataType, String[] result_out) {
    return SWAPILink.SW_GetStaticData(lh, dataCategory, dataType, result_out);
  }

  public static String SW_DealerDealStateStr(SW_DealerDealState dealerDealStateCode) {
    return SWAPILink.SW_DealerDealStateStr(dealerDealStateCode.swigValue());
  }

  public static int SW_GetBrokerIDfromSwapsWireID(int lh, long dealID, String[] brokerDealID_out) {
    return SWAPILink.SW_GetBrokerIDfromSwapsWireID(lh, dealID, brokerDealID_out);
  }

  public static int SW_BrokeredDealGetInfo(int lh, String brokerDealID, String[] dealInfo_out) {
    return SWAPILink.SW_BrokeredDealGetInfo(lh, brokerDealID, dealInfo_out);
  }

  public static int SW_GetBrokerClearingStatus(int lh, String queryXML, String[] resultXML_out) {
    return SWAPILink.SW_GetBrokerClearingStatus(lh, queryXML, resultXML_out);
  }

  public static int SW_BrokeredDealGetXML(int lh, String brokerDealID, int revisionNumber, int contractVersion, String[] resultXML_out) {
    return SWAPILink.SW_BrokeredDealGetXML(lh, brokerDealID, revisionNumber, contractVersion, resultXML_out);
  }

  public static int SW_BrokeredDealGetRecipientXML(int lh, String brokerDealID, int revisionNumber, int contractVersion, String recipientID, String[] resultXML_out) {
    return SWAPILink.SW_BrokeredDealGetRecipientXML(lh, brokerDealID, revisionNumber, contractVersion, recipientID, resultXML_out);
  }

  public static int SW_BrokeredDealGetPickupIdentityByRecipient(int lh, String brokerDealID, int revisionNumber, int contractVersion, String recipientID, String[] identity_out) {
    return SWAPILink.SW_BrokeredDealGetPickupIdentityByRecipient(lh, brokerDealID, revisionNumber, contractVersion, recipientID, identity_out);
  }

  public static int SW_BrokeredDealGetRejectReasonByRecipient(int lh, String brokerDealID, int revisionNumber, int contractVersion, String recipientID, String[] rejectReason_out) {
    return SWAPILink.SW_BrokeredDealGetRejectReasonByRecipient(lh, brokerDealID, revisionNumber, contractVersion, recipientID, rejectReason_out);
  }

  public static int SW_GetEndedDealInfo(int lh, int endedTimeStartSpan, int endedTimeCloseSpan, String[] resultXML_out) {
    return SWAPILink.SW_GetEndedDealInfo(lh, endedTimeStartSpan, endedTimeCloseSpan, resultXML_out);
  }

  public static int SW_GetEndedDealInfoEx(int lh, String queryXML, String[] queryResultXML_out) {
    return SWAPILink.SW_GetEndedDealInfoEx(lh, queryXML, queryResultXML_out);
  }

  public static int SW_DealTerminate(int lh, String brokerDealID, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealTerminate(lh, brokerDealID, newDealVersionHandle_out);
  }

  public static int SW_SubmitNewBackloadAndNovateDeal(int lh, String SWDML, String privateDataXML, String recipientsXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitNewBackloadAndNovateDeal(lh, SWDML, privateDataXML, recipientsXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitNewBrokeredDealEx(int lh, String recipientsXML, String dealXML, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitNewBrokeredDealEx(lh, recipientsXML, dealXML, newDealVersionHandle_out);
  }

  public static int SW_ReSubmitNewBrokeredDealEx(int lh, String recipientsXML, String dealXML, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_ReSubmitNewBrokeredDealEx(lh, recipientsXML, dealXML, newDealVersionHandle_out);
  }

  public static int SW_SubmitNewDirectDeal(int lh, String SWDML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitNewDirectDeal(lh, SWDML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitNewPrimeBrokerDeal(int lh, String SWDML, String privateDataXML, String recipientsXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitNewPrimeBrokerDeal(lh, SWDML, privateDataXML, recipientsXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitDraftNewDeal(int lh, String SWDML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitDraftNewDeal(lh, SWDML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitDraftNewPrimeBrokerDeal(int lh, String SWDML, String privateDataXML, String recipientsXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitDraftNewPrimeBrokerDeal(lh, SWDML, privateDataXML, recipientsXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitBackloadDeal(int lh, String SWDML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitBackloadDeal(lh, SWDML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitNewMatchDeal(int lh, String SWDML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitNewMatchDeal(lh, SWDML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitNewDirectDealEx(int lh, String SWDML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitNewDirectDealEx(lh, SWDML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitCancellationEx(int lh, String oldDealVersionHandle, String cancellationFeeXML, String privateDataXML, String recipientXML, String messageText, int effectiveDate, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitCancellationEx(lh, oldDealVersionHandle, cancellationFeeXML, privateDataXML, recipientXML, messageText, effectiveDate, newDealVersionHandle_out);
  }

  public static int SW_SubmitCancellation(int lh, String oldDealVersionHandle, String cancellationFeeXML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitCancellation(lh, oldDealVersionHandle, cancellationFeeXML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitDraftCancellation(int lh, String oldDealVersionHandle, String cancellationFeeXML, String privateDataXML, String recipientXML, String messageText, int effectiveDate, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitDraftCancellation(lh, oldDealVersionHandle, cancellationFeeXML, privateDataXML, recipientXML, messageText, effectiveDate, newDealVersionHandle_out);
  }

  public static int SW_SubmitMatchCancellationEx(int lh, String oldDealVersionHandle, String cancellationFeeXML, String privateDataXML, String recipientXML, String messageText, int effectiveDate, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitMatchCancellationEx(lh, oldDealVersionHandle, cancellationFeeXML, privateDataXML, recipientXML, messageText, effectiveDate, newDealVersionHandle_out);
  }

  public static int SW_SubmitMatchCancellation(int lh, String oldDealVersionHandle, String cancellationFeeXML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitMatchCancellation(lh, oldDealVersionHandle, cancellationFeeXML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitNettingInstruction(int lh, String nettingInstructionXML, String[] correlationId_out) {
    return SWAPILink.SW_SubmitNettingInstruction(lh, nettingInstructionXML, correlationId_out);
  }

  public static int SW_SubmitPostTradeEvent(int lh, String oldDealVersionHandle, String postTradeXML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitPostTradeEvent(lh, oldDealVersionHandle, postTradeXML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitExit(int lh, String oldDealVersionHandle, String exitReason, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitExit(lh, oldDealVersionHandle, exitReason, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitDraftAmendment(int lh, String oldDealVersionHandle, String SWDML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitDraftAmendment(lh, oldDealVersionHandle, SWDML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitUnderlying(int lh, String oldDealVersionHandle, String SWDML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitUnderlying(lh, oldDealVersionHandle, SWDML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitPrimeBrokerAmendment(int lh, String oldDealVersionHandle, String SWDML, String privateDataXML, String recipientsXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitPrimeBrokerAmendment(lh, oldDealVersionHandle, SWDML, privateDataXML, recipientsXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitNovation(int lh, String oldDealVersionHandle, String SWDML, String privateDataXML, String recipientsXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitNovation(lh, oldDealVersionHandle, SWDML, privateDataXML, recipientsXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitDraftNovation(int lh, String oldDealVersionHandle, String SWDML, String privateDataXML, String recipientsXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_SubmitDraftNovation(lh, oldDealVersionHandle, SWDML, privateDataXML, recipientsXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_DealAmendDraft(int lh, String oldDealVersionHandle, String SWDML, String privateDataXML, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealAmendDraft(lh, oldDealVersionHandle, SWDML, privateDataXML, recipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_DealAmendDraftPrimeBroker(int lh, String oldDealVersionHandle, String SWDML, String privateDataXML, String recipientsXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealAmendDraftPrimeBroker(lh, oldDealVersionHandle, SWDML, privateDataXML, recipientsXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_DealDispute(int lh, String oldDealVersionHandle, String disputeXML, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealDispute(lh, oldDealVersionHandle, disputeXML, newDealVersionHandle_out);
  }

  public static int SW_DealSendChatMessage(int lh, String oldDealVersionHandle, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealSendChatMessage(lh, oldDealVersionHandle, messageText, newDealVersionHandle_out);
  }

  public static int SW_DealPickup(int lh, String oldDealVersionHandle, String privateDataXML, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealPickup(lh, oldDealVersionHandle, privateDataXML, newDealVersionHandle_out);
  }

  public static int SW_DealAccept(int lh, String oldDealVersionHandle, String privateDataXML, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealAccept(lh, oldDealVersionHandle, privateDataXML, newDealVersionHandle_out);
  }

  public static int SW_DealAcceptAffirm(int lh, String oldDealVersionHandle, String privateDataXML, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealAcceptAffirm(lh, oldDealVersionHandle, privateDataXML, newDealVersionHandle_out);
  }

  public static int SW_DealRelease(int lh, String oldDealVersionHandle, String privateDataXML, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealRelease(lh, oldDealVersionHandle, privateDataXML, newDealVersionHandle_out);
  }

  public static int SW_DealRejectDK(int lh, String oldDealVersionHandle, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealRejectDK(lh, oldDealVersionHandle, messageText, newDealVersionHandle_out);
  }

  public static int SW_DealRequestRevision(int lh, String oldDealVersionHandle, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealRequestRevision(lh, oldDealVersionHandle, messageText, newDealVersionHandle_out);
  }

  public static int SW_DealReject(int lh, String oldDealVersionHandle, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealReject(lh, oldDealVersionHandle, messageText, newDealVersionHandle_out);
  }

  public static int SW_DealTransfer(int lh, String oldDealVersionHandle, String privateDataXML, String transferRecipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealTransfer(lh, oldDealVersionHandle, privateDataXML, transferRecipientXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_DealWithdraw(int lh, String oldDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealWithdraw(lh, oldDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_DealAcknowledge(int lh, String oldDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealAcknowledge(lh, oldDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_DealPull(int lh, String oldDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealPull(lh, oldDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_DealContinueWithNoPrimeBroker(int lh, String oldDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealContinueWithNoPrimeBroker(lh, oldDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_DealDeleteDraft(int lh, String oldDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealDeleteDraft(lh, oldDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_MatchDelete(int lh, String oldDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_MatchDelete(lh, oldDealVersionHandle, newDealVersionHandle_out);
  }

  public static String SW_DealStateStr(SW_DealState dealStateCode) {
    return SWAPILink.SW_DealStateStr(dealStateCode.swigValue());
  }

  public static int SW_QueryDefaultMisMatch(int lh, String dealVersionHandle, String[] resultXML_out) {
    return SWAPILink.SW_QueryDefaultMisMatch(lh, dealVersionHandle, resultXML_out);
  }

  public static int SW_DealGetSWML(int lh, String swmlVersion, String dealVersionHandle, String[] resultXML_out) {
    return SWAPILink.SW_DealGetSWML(lh, swmlVersion, dealVersionHandle, resultXML_out);
  }

  public static int SW_DealGetSWDML(int lh, String swdmlVersion, String dealVersionHandle, String[] resultXML_out) {
    return SWAPILink.SW_DealGetSWDML(lh, swdmlVersion, dealVersionHandle, resultXML_out);
  }

  public static int SW_DealGetUnderlyingDealSWDML(int lh, String swdmlVersion, String dealVersionHandle, String[] resultXML_out) {
    return SWAPILink.SW_DealGetUnderlyingDealSWDML(lh, swdmlVersion, dealVersionHandle, resultXML_out);
  }

  public static int SW_GetSWDMLfromSWML(int lh, String inputSWML, String[] resultXML_out) {
    return SWAPILink.SW_GetSWDMLfromSWML(lh, inputSWML, resultXML_out);
  }

  public static int SW_GetLongFromShortSWDMLEx(int lh, String inputShortFormSWDML, String recipientXML, String swdmlVersion, String[] resultXML_out) {
    return SWAPILink.SW_GetLongFromShortSWDMLEx(lh, inputShortFormSWDML, recipientXML, swdmlVersion, resultXML_out);
  }

  public static int SW_CSVToXML(int lh, String xmlType, String xmlVersion, String csvFamily, String headerRow, String dataRow, String[] resultXML_out) {
    return SWAPILink.SW_CSVToXML(lh, xmlType, xmlVersion, csvFamily, headerRow, dataRow, resultXML_out);
  }

  public static int SW_CSVGetColumn(int lh, String csvFamily, String columnName, String headerRow, String dataRow, String[] value_out) {
    return SWAPILink.SW_CSVGetColumn(lh, csvFamily, columnName, headerRow, dataRow, value_out);
  }

  public static int SW_CSVSetColumn(int lh, String csvFamily, String columnName, String newValue, String headerRow, String dataRow, String[] value_out) {
    return SWAPILink.SW_CSVSetColumn(lh, csvFamily, columnName, newValue, headerRow, dataRow, value_out);
  }

  public static int SW_DealGetVersionHandle(int lh, long dealID, int majorVersion, int privateVersion, int side, String[] dealVersionHandle_out) {
    return SWAPILink.SW_DealGetVersionHandle(lh, dealID, majorVersion, privateVersion, side, dealVersionHandle_out);
  }

  public static int SW_DealGetAllVersionHandles(int lh, long dealID, int majorVersion, int sides, String[] dealVersionHandles_out) {
    return SWAPILink.SW_DealGetAllVersionHandles(lh, dealID, majorVersion, sides, dealVersionHandles_out);
  }

  public static int SW_DealGetIDVersionsAndSide(int lh, String dealVersionHandle, long[] dealID_out, int[] majorVersion_out, int[] privateVersion_out, int[] side_out) {
    return SWAPILink.SW_DealGetIDVersionsAndSide(lh, dealVersionHandle, dealID_out, majorVersion_out, privateVersion_out, side_out);
  }

  public static int SW_DealGetMySide(int lh, long dealID, int majorVersion, int[] side_out) {
    return SWAPILink.SW_DealGetMySide(lh, dealID, majorVersion, side_out);
  }

  public static int SW_DealGetDealState(int lh, String dealVersionHandle, int[] dealState_out) {
    return SWAPILink.SW_DealGetDealState(lh, dealVersionHandle, dealState_out);
  }

  public static int SW_GetActiveDealInfo(int lh, String[] resultXML_out) {
    return SWAPILink.SW_GetActiveDealInfo(lh, resultXML_out);
  }

  public static int SW_GetParticipants(int lh, String participantQueryXML, String[] resultXML_out) {
    return SWAPILink.SW_GetParticipants(lh, participantQueryXML, resultXML_out);
  }

  public static int SW_GetLegalEntities(int lh, String legalEntityListQueryXML, String[] resultXML_out) {
    return SWAPILink.SW_GetLegalEntities(lh, legalEntityListQueryXML, resultXML_out);
  }

  public static int SW_GetMyInterestGroups(int lh, String[] resultXML_out) {
    return SWAPILink.SW_GetMyInterestGroups(lh, resultXML_out);
  }

  public static int SW_SetMyInterestGroups(int lh, String interestGroupXML) {
    return SWAPILink.SW_SetMyInterestGroups(lh, interestGroupXML);
  }

  public static int SW_GetMyBooks(int lh, String[] resultXML_out) {
    return SWAPILink.SW_GetMyBooks(lh, resultXML_out);
  }

  public static int SW_DealAffirm(int lh, String oldDealVersionHandle, String SWDML, String privateDataXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealAffirm(lh, oldDealVersionHandle, SWDML, privateDataXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_MatchUpdate(int lh, String oldDealVersionHandle, String SWDML, String privateDataXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_MatchUpdate(lh, oldDealVersionHandle, SWDML, privateDataXML, messageText, newDealVersionHandle_out);
  }

  public static int SW_SubmitValuationReport(int lh, String inputCSV) {
    return SWAPILink.SW_SubmitValuationReport(lh, inputCSV);
  }

  public static int SW_RequestValuationReport(int lh, int reportDate, String[] csv_out) {
    return SWAPILink.SW_RequestValuationReport(lh, reportDate, csv_out);
  }

  public static int SW_DealGetPrivateBookingState(int lh, long dealID, int majorVersion, int side, String[] privateBookingState_out) {
    return SWAPILink.SW_DealGetPrivateBookingState(lh, dealID, majorVersion, side, privateBookingState_out);
  }

  public static int SW_DealGetXML(int lh, String dealVersionHandle, String xmlVersion, String xmlType, String[] resultXML_out) {
    return SWAPILink.SW_DealGetXML(lh, dealVersionHandle, xmlVersion, xmlType, resultXML_out);
  }

  public static int SW_DealUpdate(int lh, String dealIdentifier, String inputXML, String[] dealUpdateResult_out) {
    return SWAPILink.SW_DealUpdate(lh, dealIdentifier, inputXML, dealUpdateResult_out);
  }

  public static int SW_DealCheckEligibility(int lh, String dealVersionHandle, String eligibilityType, String[] resultXML_out) {
    return SWAPILink.SW_DealCheckEligibility(lh, dealVersionHandle, eligibilityType, resultXML_out);
  }

  public static int SW_BatchGetOutstanding(int lh, String batchName, String[] resultXML_out) {
    return SWAPILink.SW_BatchGetOutstanding(lh, batchName, resultXML_out);
  }

  public static int SW_BatchGetDetails(int lh, int batchId, String[] resultXML_out) {
    return SWAPILink.SW_BatchGetDetails(lh, batchId, resultXML_out);
  }

  public static int SW_BatchAck(int lh, int batchId) {
    return SWAPILink.SW_BatchAck(lh, batchId);
  }

  public static int SW_BatchUpdate(int lh, String batchStatusXML, String[] resultXML_out) {
    return SWAPILink.SW_BatchUpdate(lh, batchStatusXML, resultXML_out);
  }

  public static int SW_DealSinkGetSWML(int lh, String swmlVersion, long dealID, int majorVersion, int side, String[] resultXML_out) {
    return SWAPILink.SW_DealSinkGetSWML(lh, swmlVersion, dealID, majorVersion, side, resultXML_out);
  }

  public static int SW_DealSinkDVHGetSWML(int lh, String swmlVersion, String dealVersionHandle, String[] resultXML_out) {
    return SWAPILink.SW_DealSinkDVHGetSWML(lh, swmlVersion, dealVersionHandle, resultXML_out);
  }

  public static int SW_QueryDeals(int lh, String queryXML, String[] queryResultXML_out, Object tag) {
    return SWAPILink.SW_QueryDeals(lh, queryXML, queryResultXML_out, tag);
  }

  public static int SW_ExtractGetColumns(int lh, String[] columnNames_out) {
    return SWAPILink.SW_ExtractGetColumns(lh, columnNames_out);
  }

  public static int SW_DealGetReportingStatus(int lh, String queryXML, long reserved, String[] csvResults_out) {
    return SWAPILink.SW_DealGetReportingStatus(lh, queryXML, reserved, csvResults_out);
  }

  public static int SW_DealSetReportingStatus(int lh, String reportingStatusUpdateXML, long reserved, String[] resultXML_out) {
    return SWAPILink.SW_DealSetReportingStatus(lh, reportingStatusUpdateXML, reserved, resultXML_out);
  }

  public static int SW_DealAllowDeClearingEx(int lh, String dealListXML, String[] resultXML_out) {
    return SWAPILink.SW_DealAllowDeClearingEx(lh, dealListXML, resultXML_out);
  }

  public static int SW_GetLibraryVersion() {
    return SWAPILink.SW_GetLibraryVersion();
  }

  public static int SW_GetLibraryVersionEx(String[] result_out) {
    return SWAPILink.SW_GetLibraryVersionEx(result_out);
  }

  public static int SW_ValidateXML(int lh, String inputXML, String[] errorString_out) {
    return SWAPILink.SW_ValidateXML(lh, inputXML, errorString_out);
  }

  public static int SW_TransformXML(int lh, String xsltPath, String xsltKey, String inputXML, String[] output_out) {
    return SWAPILink.SW_TransformXML(lh, xsltPath, xsltKey, inputXML, output_out);
  }

  public static int SW_SendTelemetry(int lh, String commandXML, String[] resultXML_out) {
    return SWAPILink.SW_SendTelemetry(lh, commandXML, resultXML_out);
  }

  public static int SW_DealTransferAffirm(int lh, String oldDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealTransferAffirm(lh, oldDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_DealCompare(int lh, String dealVersionHandle, String dealVersionHandle2, String[] resultXML_out) {
    return SWAPILink.SW_DealCompare(lh, dealVersionHandle, dealVersionHandle2, resultXML_out);
  }

  public static int SW_DealCompareClosestMatch(int lh, String dealVersionHandle, String[] resultXML_out) {
    return SWAPILink.SW_DealCompareClosestMatch(lh, dealVersionHandle, resultXML_out);
  }

  public static int SW_DealGetMatchInfo(int lh, String oldDealVersionHandle, String[] resultXML_out) {
    return SWAPILink.SW_DealGetMatchInfo(lh, oldDealVersionHandle, resultXML_out);
  }

  public static int SW_GetMatchInfo(int lh, String[] resultXML_out) {
    return SWAPILink.SW_GetMatchInfo(lh, resultXML_out);
  }

  public static int SW_DealSuggestMatch(int lh, String oldDealVersionHandle, String cptyDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealSuggestMatch(lh, oldDealVersionHandle, cptyDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_DealWithdrawSuggestMatch(int lh, String oldDealVersionHandle, String cptyDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_DealWithdrawSuggestMatch(lh, oldDealVersionHandle, cptyDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_MatchPush(int lh, String cptyDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_MatchPush(lh, cptyDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_MatchPull(int lh, String oldDealVersionHandle, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_MatchPull(lh, oldDealVersionHandle, newDealVersionHandle_out);
  }

  public static int SW_GateCheckDispute(int lh, String oldDealVersionHandle, String recipientXML, String messageText, String[] newDealVersionHandle_out) {
    return SWAPILink.SW_GateCheckDispute(lh, oldDealVersionHandle, recipientXML, messageText, newDealVersionHandle_out);
  }

}
