/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.swapswire.sw_api;

public final class SWDA_DealType {
  public final static SWDA_DealType SWDT_New = new SWDA_DealType("SWDT_New");
  public final static SWDA_DealType SWDT_Draft = new SWDA_DealType("SWDT_Draft");
  public final static SWDA_DealType SWDT_Backload = new SWDA_DealType("SWDT_Backload");
  public final static SWDA_DealType SWDT_PrimeBroker = new SWDA_DealType("SWDT_PrimeBroker");
  public final static SWDA_DealType SWDT_PrimeBrokerDraft = new SWDA_DealType("SWDT_PrimeBrokerDraft");
  public final static SWDA_DealType SWDT_Novation = new SWDA_DealType("SWDT_Novation");
  public final static SWDA_DealType SWDT_Underlying = new SWDA_DealType("SWDT_Underlying");
  public final static SWDA_DealType SWDT_Match = new SWDA_DealType("SWDT_Match");
  public final static SWDA_DealType SWDT_Auto = new SWDA_DealType("SWDT_Auto");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SWDA_DealType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SWDA_DealType.class + " with value " + swigValue);
  }

  private SWDA_DealType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SWDA_DealType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SWDA_DealType(String swigName, SWDA_DealType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SWDA_DealType[] swigValues = { SWDT_New, SWDT_Draft, SWDT_Backload, SWDT_PrimeBroker, SWDT_PrimeBrokerDraft, SWDT_Novation, SWDT_Underlying, SWDT_Match, SWDT_Auto };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

