/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.swapswire.sw_api;

public final class SW_CallbackMode {
  public final static SW_CallbackMode SWCM_Synchronous = new SW_CallbackMode("SWCM_Synchronous");
  public final static SW_CallbackMode SWCM_Asynchronous = new SW_CallbackMode("SWCM_Asynchronous");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SW_CallbackMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SW_CallbackMode.class + " with value " + swigValue);
  }

  private SW_CallbackMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SW_CallbackMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SW_CallbackMode(String swigName, SW_CallbackMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SW_CallbackMode[] swigValues = { SWCM_Synchronous, SWCM_Asynchronous };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

