/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.swapswire.sw_api;

public final class SW_DealState {
  public final static SW_DealState SWDS_Err = new SW_DealState("SWDS_Err", -1);
  public final static SW_DealState SWDS_PendingBrokeredDeal = new SW_DealState("SWDS_PendingBrokeredDeal");
  public final static SW_DealState SWDS_PendingDirectDeal = new SW_DealState("SWDS_PendingDirectDeal");
  public final static SW_DealState SWDS_BrokeredPickedUp = new SW_DealState("SWDS_BrokeredPickedUp");
  public final static SW_DealState SWDS_AwaitingCptyAccept = new SW_DealState("SWDS_AwaitingCptyAccept");
  public final static SW_DealState SWDS_AwaitingCptyAction = new SW_DealState("SWDS_AwaitingCptyAction");
  public final static SW_DealState SWDS_AwaitingCptyActionRef = new SW_DealState("SWDS_AwaitingCptyActionRef");
  public final static SW_DealState SWDS_AwaitingMyAction = new SW_DealState("SWDS_AwaitingMyAction");
  public final static SW_DealState SWDS_AwaitingMyActionRef = new SW_DealState("SWDS_AwaitingMyActionRef");
  public final static SW_DealState SWDS_AffirmedDeal = new SW_DealState("SWDS_AffirmedDeal");
  public final static SW_DealState SWDS_AwaitingBrokerAction = new SW_DealState("SWDS_AwaitingBrokerAction");
  public final static SW_DealState SWDS_AwaitingAcknowledgement = new SW_DealState("SWDS_AwaitingAcknowledgement");
  public final static SW_DealState SWDS_Terminated = new SW_DealState("SWDS_Terminated");
  public final static SW_DealState SWDS_Transferred = new SW_DealState("SWDS_Transferred");
  public final static SW_DealState SWDS_Released = new SW_DealState("SWDS_Released");
  public final static SW_DealState SWDS_PendingDirectDealWithMe = new SW_DealState("SWDS_PendingDirectDealWithMe");
  public final static SW_DealState SWDS_PendingDirectDealWithCpty = new SW_DealState("SWDS_PendingDirectDealWithCpty");
  public final static SW_DealState SWDS_PendingDirectDealWithCptyPulled = new SW_DealState("SWDS_PendingDirectDealWithCptyPulled");
  public final static SW_DealState SWDS_UnsentDeal = new SW_DealState("SWDS_UnsentDeal");
  public final static SW_DealState SWDS_IncomingTransfer = new SW_DealState("SWDS_IncomingTransfer");
  public final static SW_DealState SWDS_PrimeBrokerAgreed = new SW_DealState("SWDS_PrimeBrokerAgreed");
  public final static SW_DealState SWDS_PrimeBrokerAccepted = new SW_DealState("SWDS_PrimeBrokerAccepted");
  public final static SW_DealState SWDS_PrimeBrokerRevisionPending = new SW_DealState("SWDS_PrimeBrokerRevisionPending");
  public final static SW_DealState SWDS_PrimeBrokerAgreementPending = new SW_DealState("SWDS_PrimeBrokerAgreementPending");
  public final static SW_DealState SWDS_ContinueWithNoPrimeBroker = new SW_DealState("SWDS_ContinueWithNoPrimeBroker");
  public final static SW_DealState SWDS_NovationFeeAgreedWithCounterparty = new SW_DealState("SWDS_NovationFeeAgreedWithCounterparty");
  public final static SW_DealState SWDS_NovationFeeAgreementPending = new SW_DealState("SWDS_NovationFeeAgreementPending");
  public final static SW_DealState SWDS_IncomingRemainingAgreementPending = new SW_DealState("SWDS_IncomingRemainingAgreementPending");
  public final static SW_DealState SWDS_PendingMatchWithCpty = new SW_DealState("SWDS_PendingMatchWithCpty");
  public final static SW_DealState SWDS_PendingMatchWithMe = new SW_DealState("SWDS_PendingMatchWithMe");
  public final static SW_DealState SWDS_TerminatedByMatch = new SW_DealState("SWDS_TerminatedByMatch");
  public final static SW_DealState SWDS_Unsent = new SW_DealState("SWDS_Unsent");
  public final static SW_DealState SWDS_Active = new SW_DealState("SWDS_Active");
  public final static SW_DealState SWDS_Withdrawn = new SW_DealState("SWDS_Withdrawn");
  public final static SW_DealState SWDS_Accepted = new SW_DealState("SWDS_Accepted");
  public final static SW_DealState SWDS_ObsoleteVersion = new SW_DealState("SWDS_ObsoleteVersion");
  public final static SW_DealState SWDS_DealUpdated = new SW_DealState("SWDS_DealUpdated");
  public final static SW_DealState SWDS_MatchInfo = new SW_DealState("SWDS_MatchInfo");
  public final static SW_DealState SWDS_ReportInfo = new SW_DealState("SWDS_ReportInfo");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SW_DealState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SW_DealState.class + " with value " + swigValue);
  }

  private SW_DealState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SW_DealState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SW_DealState(String swigName, SW_DealState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SW_DealState[] swigValues = { SWDS_Err, SWDS_PendingBrokeredDeal, SWDS_PendingDirectDeal, SWDS_BrokeredPickedUp, SWDS_AwaitingCptyAccept, SWDS_AwaitingCptyAction, SWDS_AwaitingCptyActionRef, SWDS_AwaitingMyAction, SWDS_AwaitingMyActionRef, SWDS_AffirmedDeal, SWDS_AwaitingBrokerAction, SWDS_AwaitingAcknowledgement, SWDS_Terminated, SWDS_Transferred, SWDS_Released, SWDS_PendingDirectDealWithMe, SWDS_PendingDirectDealWithCpty, SWDS_PendingDirectDealWithCptyPulled, SWDS_UnsentDeal, SWDS_IncomingTransfer, SWDS_PrimeBrokerAgreed, SWDS_PrimeBrokerAccepted, SWDS_PrimeBrokerRevisionPending, SWDS_PrimeBrokerAgreementPending, SWDS_ContinueWithNoPrimeBroker, SWDS_NovationFeeAgreedWithCounterparty, SWDS_NovationFeeAgreementPending, SWDS_IncomingRemainingAgreementPending, SWDS_PendingMatchWithCpty, SWDS_PendingMatchWithMe, SWDS_TerminatedByMatch, SWDS_Unsent, SWDS_Active, SWDS_Withdrawn, SWDS_Accepted, SWDS_ObsoleteVersion, SWDS_DealUpdated, SWDS_MatchInfo, SWDS_ReportInfo };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

