/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.swapswire.sw_api;

public final class SW_TradeAttributeFlags {
  public final static SW_TradeAttributeFlags SWTA_Synthesised = new SW_TradeAttributeFlags("SWTA_Synthesised", 0x1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SW_TradeAttributeFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SW_TradeAttributeFlags.class + " with value " + swigValue);
  }

  private SW_TradeAttributeFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SW_TradeAttributeFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SW_TradeAttributeFlags(String swigName, SW_TradeAttributeFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SW_TradeAttributeFlags[] swigValues = { SWTA_Synthesised };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

